juno and hikey M-LCR: update to use gcc 6.3 linaro
use gcc6.3-linaro for kernel compilation, and android components
that not use clang for compilation

And for x15 build, we need to set BOARD_USES_FULL_RECOVERY_IMAGE=true
to workaround the recovery.img generattion,
otherwise we will get error like following:
[ 49% 520/1058] /bin/bash -c "(mkdir -p out/target/product/am57xevm/obj/PACKAGING/recovery_patch_intermediates/ ) && (PATH=out/host/linux-x86/bin:\$PATH out/host/linux-x86/bin/imgdiff out/target/product/am57xevm/boot.img out/target/product/am57xevm/recovery.img out/target/product/am57xevm/obj/PACKAGING/recovery_patch_intermediates/recovery_from_boot.p )"
FAILED: /bin/bash -c "(mkdir -p out/target/product/am57xevm/obj/PACKAGING/recovery_patch_intermediates/ ) && (PATH=out/host/linux-x86/bin:\$PATH out/host/linux-x86/bin/imgdiff out/target/product/am57xevm/boot.img out/target/product/am57xevm/recovery.img out/target/product/am57xevm/obj/PACKAGING/recovery_patch_intermediates/recovery_from_boot.p )"
Error: footer size 1831868195 != decompressed size 0
failed to break apart source image

Change-Id: I978545424f71bfae9d5cb981a5d8f0bdf45ce8a5
Signed-off-by: Yongqin Liu <yongqin.liu@linaro.org>